name: CI
on:
  workflow_run:
    workflows: ["Build FIPS zips"]
    types:
      - completed

jobs:
  # --------------------- FIPS build tests ------------------------------
  # Build wolfcryptjni against wolfSSL FIPS Ready, v2, v5, v6
  # Only testing one Linux for starters, with one JDK/version
  # Once fips_check.sh script gets modified to work with bash < 4, which
  # is the default for MacOS, MacOS targets will be added here.
  fips-ready-build:
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        jdk_version: [ '21' ]
        wolfssl_configure: [ '--enable-fips=ready --enable-jni' ]
    name: FIPS Ready Build (${{ matrix.os }} Zulu JDK ${{ matrix.jdk_version }})
    uses: ./.github/workflows/fips.yml
    with:
      os: ${{ matrix.os }}
      jdk_distro: "zulu"
      jdk_version: ${{ matrix.jdk_version }}
      wolfssl_configure: ${{ matrix.wolfssl_configure }}
      fips_check_variant: "fips-ready"

