name: CI
on:
  push:
    branches: [ 'master', 'main', 'fsanitizeAction', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
  # ------------------ fsanitize=address build --------------------------
  # Only check one Linux and Mac JDK version as a sanity check. Using Zulu,
  # but this can be expanded if needed.
  # wolfSSL ./configure:
  #     --enable-jni CFLAGS="-fsanitize=address" LDFLAGS="-fsanitize=address"
  linux-zulu-fsanitize-address:
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        jdk_version: [ '11' ]
        wolfssl_configure: [ '--enable-jni --enable-debug CFLAGS="-fsanitize=address" LDFLAGS="-fsanitize=address"' ]
        wolfcryptjni_cflags: [ '-fsanitize=address -g' ]
        wolfcryptjni_ldflags: [ '-fsanitize=address' ]
    name: ${{ matrix.os }} (fsanitize=address | Zulu JDK ${{ matrix.jdk_version }}, ${{ matrix.wolfssl_configure}})
    uses: ./.github/workflows/linux-common.yml
    with:
      os: ${{ matrix.os }}
      jdk_distro: "zulu"
      jdk_version: ${{ matrix.jdk_version }}
      wolfssl_configure: ${{ matrix.wolfssl_configure }}
      wolfcryptjni_cflags: ${{ matrix.wolfcryptjni_cflags }}
      wolfcryptjni_ldflags: ${{ matrix.wolfcryptjni_ldflags }}
      preload_libasan: true

